---
lc:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

all:
  hosts:
    host1:
      ansible_connection: local
    host2:
      ansible_connection: local
    host3:
      ansible_connection: local

  vars:
    installation_method: "archive"
    product_version: "6.0.1"
    cli_version: 2.1
    connect_connectors: 
      cc1:
      cc2:

connect:
  hosts:
    host2:
    host3:
  vars:
    connectors:
      it1:
      it2:

broker:
  hosts:
    host1:
    host2:
  vars:
    connectors:
      - it1:
      - it2:

elastic_connector:
  hosts:
    host2:
    host1: